[build]
    publish = "_site/"
    command = "npm run build"
[build.processing]
  skip_processing = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/campervan-eve"
  to = "/electric-campervans/eve"

[[redirects]]
  from = "/our-vans"
  to = "/"

[[redirects]]
  from = "/electric-campervans"
  to = "/"

[[redirects]]
  from = "/our-vans/*"
  to = "/electric-campervans/:splat"

[[redirects]]
  from = "/million-pound-homes"
  to = "/blog/million-pound-motorhomes"
