[build]
    publish = "_site/"
    command = "npm run build"
[build.processing]
  skip_processing = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/campervan-eve"
  to = "/our-vans/eve"
  from = "/million-pound-homes"
  to = "/blog/million-pound-homes"
